# Generated by Django 2.0.5 on 2018-08-19 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BoardTable',
            new_name='Post',
        ),
    ]
