# Generated by Django 2.0.5 on 2018-08-21 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20180820_0516'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='photo',
            field=models.FileField(blank=True, upload_to='media/%Y/%m/%d'),
        ),
    ]
