# Generated by Django 2.0.5 on 2018-08-21 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_post_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='photo',
            new_name='files',
        ),
    ]
