# Generated by Django 2.0.5 on 2018-08-22 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_auto_20180821_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='files',
            field=models.FileField(blank=True, upload_to='photo/%Y/%m/%d'),
        ),
    ]
