# Generated by Django 2.0.5 on 2018-09-07 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_auto_20180822_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='files',
            field=models.ImageField(blank=True, upload_to='photo/%Y%m%d'),
        ),
    ]
